import { FormState } from './types';

export const cameraMovements = [
    { value: 'Static Shot', label: 'Static Shot (Tangkapan Statis)' },
    { value: 'Pan', label: 'Pan (Geser Horizontal)' },
    { value: 'Tilt', label: 'Tilt (Geser Vertikal)' },
    { value: 'Zoom In', label: 'Zoom In (Perbesar)' },
    { value: 'Zoom Out', label: 'Zoom Out (Perkecil)' },
    { value: 'Dolly', label: 'Dolly (Maju/Mundur)' },
    { value: 'Truck', label: 'Truck (Geser Kiri/Kanan)' },
    { value: 'Pedestal', label: 'Pedestal (Naik/Turun)' },
    { value: 'Roll', label: 'Roll (Putar Sumbu)' },
    { value: 'Arc', label: 'Arc (Gerakan Melengkung)' },
    { value: 'Boom / Crane', label: 'Boom / Crane (Gerakan Derek)' },
    { value: 'Tracking / Follow Shot', label: 'Tracking / Follow Shot (Tangkapan Mengikuti)' },
    { value: 'Handheld Shot', label: 'Handheld Shot (Tangkapan Genggam)' },
    { value: 'Whip Pan', label: 'Whip Pan (Geser Cepat)' },
    { value: 'Zolly / Dolly Zoom', label: 'Zolly / Dolly Zoom (Efek Vertigo)' },
    { value: '3D Rotation', label: '3D Rotation (Rotasi 3D)' },
    { value: 'Orbit', label: 'Orbit (Mengorbit)' },
    { value: 'Fly-through', label: 'Fly-through (Terbang Melintas)' },
    { value: 'Slow Motion', label: 'Slow Motion (Gerak Lambat)' },
    { value: 'Fast Motion', label: 'Fast Motion (Gerak Cepat)' },
];

export const timeOptions = [
    { value: 'Pagi Hari (Sunrise)', label: 'Pagi Hari (Sunrise)' },
    { value: 'Siang Hari (Midday)', label: 'Siang Hari (Midday)' },
    { value: 'Sore Hari (Afternoon)', label: 'Sore Hari (Afternoon)' },
    { value: 'Senja (Golden Hour)', label: 'Senja (Golden Hour)' },
    { value: 'Malam Hari (Night)', label: 'Malam Hari (Night)' },
    { value: 'Blue Hour', label: 'Blue Hour' },
];

export const lightingOptions = [
    { value: 'Natural Light', label: 'Cahaya Alami (Natural Light)' },
    { value: 'Golden Hour', label: 'Golden Hour' },
    { value: 'Blue Hour', label: 'Blue Hour' },
    { value: 'High-key', label: 'High-key (Cerah)' },
    { value: 'Low-key', label: 'Low-key (Gelap & Dramatis)' },
    { value: 'Backlight', label: 'Backlight (Cahaya dari Belakang)' },
    { value: 'Studio Lighting', label: 'Pencahayaan Studio' },
    { value: 'Neon Lights', label: 'Lampu Neon' },
];

export const styleOptions = [
    { value: 'Cinematic', label: 'Sinematik (Cinematic)' },
    { value: 'Hyper-realistic', label: 'Hiper-realistis' },
    { value: 'Documentary', label: 'Dokumenter' },
    { value: 'Anime', label: 'Anime' },
    { value: '3D Animation', label: 'Animasi 3D' },
    { value: 'Vintage Film', label: 'Film Vintage' },
    { value: 'Black and White', label: 'Hitam Putih' },
    { value: 'Vlog Style', label: 'Gaya Vlog' },
];

export const moodOptions = [
    { value: 'Nostalgic', label: 'Nostalgia (Nostalgic)' },
    { value: 'Joyful', label: 'Gembira (Joyful)' },
    { value: 'Suspenseful', label: 'Mencekam (Suspenseful)' },
    { value: 'Peaceful', label: 'Damai (Peaceful)' },
    { value: 'Energetic', label: 'Penuh Energi (Energetic)' },
    { value: 'Romantic', label: 'Romantis' },
    { value: 'Mysterious', label: 'Misterius' },
    { value: 'Melancholic', label: 'Melankolis' },
];

export const tenseActionExamples: FormState[] = [
    {
        title: "Pelarian di Gang Sempit Myeongdong",
        name: "Kim Ji-eun",
        gender: "Perempuan",
        age: "24",
        origin: "Seoul, Korea Selatan",
        hair: "Rambut hitam sebahu, acak-acakan karena berlari",
        clothing: "Jaket kulit hitam usang di atas hoodie abu-abu, celana kargo gelap",
        skinColor: "Pucat karena kelelahan dan adrenalin",
        action: "Berlari cepat melewati gang sempit yang basah dan remang-remang, napasnya terengah-engah saat melompati tumpukan kotak",
        expression: "Wajah tegang, mata waspada melirik ke belakang, rahang mengeras",
        location: "Gang belakang yang dipenuhi grafiti di Myeongdong, diterangi oleh lampu neon yang berkedip",
        time: "Malam Hari (Night)",
        cameraMovement: "Handheld Shot",
        lighting: "Neon Lights",
        videoStyle: "Cinematic",
        videoMood: "Suspenseful",
        sound: "Deru langkah kaki yang menggema, napas terengah-engah, sirene polisi samar di kejauhan",
        dialogue: "Aku tidak bisa kembali ke sana.",
        additionalDetails: "Genangan air memantulkan cahaya neon yang berwarna-warni. Uap keluar dari mulutnya di udara malam yang dingin.",
        negativePrompt: "cerah, santai, karakter tersenyum",
    },
    {
        title: "Peretas di Bawah Lampu Neon",
        name: "Park So-yeon ('Nyx')",
        gender: "Perempuan",
        age: "22",
        origin: "Busan, Korea Selatan",
        hair: "Potongan bob asimetris berwarna ungu terang",
        clothing: "Jaket bomber oversized, kaus band metal, dan celana jeans robek",
        skinColor: "Putih susu",
        action: "Mengetik dengan kecepatan kilat di laptopnya, beberapa monitor di sekelilingnya menampilkan baris kode yang bergerak cepat dan peta digital",
        expression: "Sangat fokus, alis berkerut dalam konsentrasi, bibir bawahnya digigit",
        location: "Apartemen loteng yang berantakan, dipenuhi perangkat keras komputer dan kabel",
        time: "Malam Hari (Night)",
        cameraMovement: "Slow Motion",
        lighting: "Hanya cahaya dari monitor dan lampu neon ungu di dinding",
        videoStyle: "Hyper-realistic",
        videoMood: "Mysterious",
        sound: "Klik cepat keyboard, dengungan kipas server, musik lofi-hiphop instrumental",
        dialogue: "Hampir... masuk.",
        additionalDetails: "Kaleng minuman energi kosong berserakan di mejanya. Pantulan kode terlihat di kacamatanya.",
        negativePrompt: "kantor rapi, siang hari, formal",
    },
    {
        title: "Konfrontasi di Atap Gedung",
        name: "Lee Ha-na",
        gender: "Perempuan",
        age: "29",
        origin: "Incheon, Korea Selatan",
        hair: "Kuncir kuda tinggi yang praktis, beberapa helai rambut lepas tertiup angin",
        clothing: "Setelan bisnis hitam yang ramping, kemeja putih sedikit terbuka di kerah",
        skinColor: "Sawo matang",
        action: "Berdiri tegap di tepi atap, menghadapi seorang antagonis yang tidak terlihat, angin meniup jasnya",
        expression: "Dingin, terkendali, mata menyipit dengan tekad baja",
        location: "Atap gedung pencakar langit di Gangnam, dengan pemandangan kota Seoul di malam hari",
        time: "Senja (Golden Hour)",
        cameraMovement: "Arc",
        lighting: "Golden Hour",
        videoStyle: "Cinematic",
        videoMood: "Suspenseful",
        sound: "Angin menderu, lalu lintas kota yang jauh di bawah, keheningan yang menegangkan",
        dialogue: "Ini harus berakhir. Di sini. Sekarang.",
        additionalDetails: "Hujan gerimis mulai turun, membuat permukaan atap berkilau. Logo perusahaan neon di gedung seberang berkedip.",
        negativePrompt: "lucu, komedi, cuaca cerah",
    },
    {
        title: "Misi Penyamaran di Pesta Mewah",
        name: "Choi Soo-min",
        gender: "Perempuan",
        age: "26",
        origin: "Seoul, Korea Selatan",
        hair: "Sanggul elegan yang rumit, dihiasi jepit rambut permata",
        clothing: "Gaun malam sutra merah yang memukau dengan belahan tinggi",
        skinColor: "Cerah dan mulus",
        action: "Berbaur dengan anggun di antara kerumunan, matanya diam-diam memindai ruangan untuk mencari targetnya sambil memegang segelas sampanye",
        expression: "Senyum sosialita yang menawan, tetapi matanya menunjukkan kewaspadaan yang tajam",
        location: "Ballroom hotel bintang lima yang mewah, dipenuhi tamu-tamu elit",
        time: "Malam Hari (Night)",
        cameraMovement: "Tracking / Follow Shot",
        lighting: "Lampu kristal yang lembut dan berkilauan",
        videoStyle: "Cinematic",
        videoMood: "Mysterious",
        sound: "Obrolan lembut, musik orkestra klasik, denting gelas",
        dialogue: "",
        additionalDetails: "Dia menyentuh antingnya dengan gugup, yang sebenarnya adalah alat komunikasi tersembunyi. Pantulan ruangan terlihat di sampanyenya.",
        negativePrompt: "pakaian kasual, tempat kumuh, keributan",
    },
    {
        title: "Balapan Liar di Jalanan Seoul",
        name: "Kang Yoo-ra",
        gender: "Perempuan",
        age: "25",
        origin: "Daegu, Korea Selatan",
        hair: "Diwarnai pirang platinum, diikat ke belakang",
        clothing: "Jaket balap kulit dengan patch, tank top putih, sarung tangan mengemudi tanpa jari",
        skinColor: "Terawat",
        action: "Menggenggam setir dengan erat, melakukan drift di tikungan tajam, menyalip mobil lain dengan kecepatan tinggi",
        expression: "Adrenalin murni, seringai percaya diri bercampur dengan konsentrasi intens",
        location: "Jalanan basah karena hujan di pusat kota Seoul, dikelilingi oleh gedung-gedung tinggi dengan lampu neon",
        time: "Malam Hari (Night)",
        cameraMovement: "Whip Pan",
        lighting: "Lampu jalan dan neon yang kabur karena kecepatan, menciptakan jejak cahaya",
        videoStyle: "Energetic",
        videoMood: "Energetic",
        sound: "Deru mesin yang dimodifikasi, decitan ban, musik K-HipHop yang menghentak",
        dialogue: "Coba saja kejar aku!",
        additionalDetails: "Tetesan hujan menghantam kaca depan. Speedometer menunjukkan angka yang sangat tinggi.",
        negativePrompt: "lalu lintas padat, mengemudi pelan, siang hari",
    },
    {
        title: "Pemburu Artefak di Kuil Kuno",
        name: "Yoon Seo-ah",
        gender: "Perempuan",
        age: "31",
        origin: "Gyeongju, Korea Selatan",
        hair: "Dikepang rapi ke samping",
        clothing: "Pakaian petualang praktis, celana kargo, sepatu bot hiking, membawa ransel kulit",
        skinColor: "Agak gelap karena matahari",
        action: "Meniup debu dari sebuah ukiran kuno di dinding batu, matanya memindai simbol-simbol dengan hati-hati",
        expression: "Kagum dan penuh rasa ingin tahu, dipadukan dengan keseriusan seorang sarjana",
        location: "Di dalam ruang tersembunyi sebuah kuil kuno di pegunungan",
        time: "Siang Hari (Midday)",
        cameraMovement: "Dolly",
        lighting: "Sinar matahari yang masuk melalui celah di langit-langit, menciptakan pilar cahaya berdebu",
        videoStyle: "Cinematic",
        videoMood: "Mysterious",
        sound: "Keheningan yang dalam, tetesan air yang menggema, gemerisik langkah kakinya",
        dialogue: "Ini... ini dia petunjuknya.",
        additionalDetails: "Jaring laba-laba menutupi sudut-sudut ruangan. Dia memegang buku catatan tua yang sudah usang.",
        negativePrompt: "kota modern, teknologi, kebisingan",
    },
    {
        title: "Negosiasi Tegang di Dermaga",
        name: "Han Chae-rin",
        gender: "Perempuan",
        age: "35",
        origin: "Busan, Korea Selatan",
        hair: "Potongan rambut bob pendek yang tajam dan profesional",
        clothing: "Mantel parit (trench coat) berwarna krem di atas blus sutra",
        skinColor: "Putih",
        action: "Berdiri di antara kontainer pengiriman, bertukar pandang dengan sekelompok pria berjas, tangannya di dalam saku mantel",
        expression: "Tenang di permukaan, tetapi matanya menunjukkan perhitungan yang tajam dan sedikit bahaya",
        location: "Dermaga pelabuhan Busan yang berkabut saat fajar",
        time: "Pagi Hari (Sunrise)",
        cameraMovement: "Zoom In",
        lighting: "Cahaya pagi yang pucat dan berkabut, menciptakan siluet",
        videoStyle: "Cinematic",
        videoMood: "Suspenseful",
        sound: "Teriakan burung camar, klakson kapal yang jauh, desiran ombak lembut",
        dialogue: "Tawaran saya tidak berubah.",
        additionalDetails: "Kabut tebal mengaburkan jarak. Dia bisa melihat napasnya sendiri di udara dingin.",
        negativePrompt: "pasar yang ramai, cuaca cerah, suasana bahagia",
    },
    {
        title: "Bertahan di Kereta Bawah Tanah",
        name: "Moon Eun-ji",
        gender: "Perempuan",
        age: "20",
        origin: "Seoul, Korea Selatan",
        hair: "Berantakan, wajahnya kotor",
        clothing: "Seragam sekolah yang sobek dan kotor",
        skinColor: "Pucat",
        action: "Mendekam di antara kursi di gerbong kereta bawah tanah yang ditinggalkan, mencengkeram pipa logam sebagai senjata darurat",
        expression: "Ketakutan, tetapi matanya menunjukkan kilatan perlawanan",
        location: "Gerbong kereta bawah tanah yang berhenti di terowongan gelap",
        time: "Malam Hari (Night)",
        cameraMovement: "Pedestal",
        lighting: "Lampu darurat merah yang berkedip-kedip secara sporadis, menciptakan bayangan panjang",
        videoStyle: "Hyper-realistic",
        videoMood: "Suspenseful",
        sound: "Keheningan yang menakutkan, diselingi oleh suara tetesan air dan suara gesekan logam yang tidak diketahui asalnya",
        dialogue: "",
        additionalDetails: "Iklan di dinding gerbong sudah usang dan terkelupas. Ada tas punggung yang tergeletak di lantai.",
        negativePrompt: "kereta bersih, penumpang ramai, terang",
    },
    {
        title: "Duel di Hutan Bambu",
        name: "Jang Mi-na",
        gender: "Perempuan",
        age: "28",
        origin: "Damyang, Korea Selatan",
        hair: "Dikuncir tinggi, beberapa helai menempel di pelipisnya yang berkeringat",
        clothing: "Pakaian latihan bela diri tradisional (Dobok) berwarna putih",
        skinColor: "Sehat",
        action: "Dalam posisi bertarung yang rendah, bergerak mengitari lawannya dengan pedang kayu (mokgeom), batang bambu menjulang di sekelilingnya",
        expression: "Fokus yang smat tajam, napas terkendali, mata tidak pernah lepas dari lawannya",
        location: "Hutan Bambu Juknokwon di Damyang",
        time: "Sore Hari (Afternoon)",
        cameraMovement: "Orbit",
        lighting: "Cahaya matahari yang belang-belang menembus celah-celah bambu yang lebat",
        videoStyle: "Cinematic",
        videoMood: "Energetic",
        sound: "Desir daun bambu yang tertiup angin, seruan sesekali (kihap), benturan pedang kayu",
        dialogue: "",
        additionalDetails: "Daun-daun kering berputar-putar di sekitar kaki mereka saat mereka bergerak. Bayangan panjang dan tipis dari bambu menciptakan pola seperti jeruji.",
        negativePrompt: "perkotaan, pertarungan senjata api, malam hari",
    },
    {
        title: "Saksi Kunci yang Diburu",
        name: "Bae Soo-jung",
        gender: "Perempuan",
        age: "27",
        origin: "Suwon, Korea Selatan",
        hair: "Tergerai alami, dia terus-menerus merapikannya dengan gugup",
        clothing: "Sweter sederhana, jeans, dan kacamata berbingkai tebal",
        skinColor: "Cerah",
        action: "Duduk di kafe yang ramai, mencoba untuk terlihat biasa saja sambil dengan cemas melirik ke arah pintu setiap kali bel berbunyi",
        expression: "Gugup, paranoid, mencoba menyembunyikan kepanikannya di balik secangkir kopi",
        location: "Kafe yang nyaman dan ramai di area universitas Hongdae",
        time: "Siang Hari (Midday)",
        cameraMovement: "Zoom Out",
        lighting: "Natural Light",
        videoStyle: "Documentary",
        videoMood: "Suspenseful",
        sound: "Obrolan mahasiswa, suara mesin espresso, musik indie yang diputar pelan",
        dialogue: "Mereka seharusnya sudah ada di sini.",
        additionalDetails: "Tangannya sedikit gemetar saat mengangkat cangkir. Dia memegang ponsel di bawah meja, siap untuk menelepon.",
        negativePrompt: "kosong, sunyi, mewah",
    }
];
